version: '2'
services:
  redis: 
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
      
  beigin:
    build: "."
    entrypoint: "dlv debug ./begin -l 0.0.0.0:2345 --headless=true --log=true -- server"
    ports:
      - "2345:2345"
    expose:
      - "2345"